name: TypeScript Compilation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tsc:
    name: Compile TypeScript
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install

    - name: Compile TypeScript
      uses: iCrawl/action-tsc@v1
